# Generated by Django 3.2.7 on 2021-12-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('product_visibility', models.IntegerField(default=1)),
                ('Product_rate', models.IntegerField(default=1)),
            ],
        ),
    ]
