# Generated by Django 3.2.7 on 2021-12-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item',
            new_name='product',
        ),
    ]
