# Generated by Django 3.2.7 on 2021-12-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_rename_item_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_dicpriction',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
