# Generated by Django 3.2.7 on 2021-12-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestedserializer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ratings',
            field=models.IntegerField(),
        ),
    ]
